export type HalftoneShape = 'circle' | 'triangle' | 'square' | 'diamond';
export type HalftoneSettings = { color: string; minSize: number; maxSize: number; spacing: number; contrast: number; ppi: number; shape: HalftoneShape };
export type HalftoneDot = { x: number; y: number; diameter: number };
const BACKGROUND_LUMINANCE_CUTOFF = 250;
export function clamp(value: number, min: number, max: number) { return Math.min(max, Math.max(min, value)); }
function luminanceAt(data: Uint8ClampedArray, width: number, x: number, y: number) { const i = (y * width + x) * 4; const alpha = data[i + 3] / 255; return (0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2]) * alpha + 255 * (1 - alpha); }
export function createHalftoneDots(data: Uint8ClampedArray, width: number, height: number, settings: HalftoneSettings): HalftoneDot[] {
  const spacing = Math.max(1, settings.spacing), minSize = clamp(settings.minSize, 0, 80), maxSize = Math.max(minSize, clamp(settings.maxSize, 0, 80)), contrast = settings.contrast / 100; const dots: HalftoneDot[] = [];
  for (let y = spacing / 2; y < height; y += spacing) { const sy = Math.min(height - 1, Math.floor(y)); for (let x = spacing / 2; x < width; x += spacing) { const sx = Math.min(width - 1, Math.floor(x)); let value = luminanceAt(data, width, sx, sy); if (value >= BACKGROUND_LUMINANCE_CUTOFF) continue; value = clamp(128 + (value - 128) * contrast, 0, 255); const diameter = minSize + (maxSize - minSize) * (1 - value / 255); if (diameter > 0.01) dots.push({ x, y, diameter }); } }
  return dots;
}
export function drawHalftoneDot(context: CanvasRenderingContext2D, shape: HalftoneShape, x: number, y: number, diameter: number) { const half = diameter / 2; context.beginPath(); if (shape === 'triangle') { context.moveTo(x, y - half); context.lineTo(x + half, y + half); context.lineTo(x - half, y + half); } else if (shape === 'square') context.rect(x - half, y - half, diameter, diameter); else if (shape === 'diamond') { context.moveTo(x, y - half); context.lineTo(x + half, y); context.lineTo(x, y + half); context.lineTo(x - half, y); } else context.arc(x, y, half, 0, Math.PI * 2); context.closePath(); context.fill(); }
export function dotToSvg(shape: HalftoneShape, { x, y, diameter }: HalftoneDot) { const half = diameter / 2, n = (value: number) => value.toFixed(2); if (shape === 'triangle') return `<polygon points="${n(x)},${n(y - half)} ${n(x + half)},${n(y + half)} ${n(x - half)},${n(y + half)}"/>`; if (shape === 'square') return `<rect x="${n(x - half)}" y="${n(y - half)}" width="${n(diameter)}" height="${n(diameter)}"/>`; if (shape === 'diamond') return `<polygon points="${n(x)},${n(y - half)} ${n(x + half)},${n(y)} ${n(x)},${n(y + half)} ${n(x - half)},${n(y)}"/>`; return `<circle cx="${n(x)}" cy="${n(y)}" r="${n(half)}"/>`; }
export function buildHalftoneSvg(width: number, height: number, dots: HalftoneDot[], settings: HalftoneSettings) { return ['<?xml version="1.0" encoding="UTF-8"?>', `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">`, '<rect width="100%" height="100%" fill="#FFFFFF"/>', `<g fill="${settings.color.toUpperCase()}">`, dots.map(dot => dotToSvg(settings.shape, dot)).join(''), '</g>', '</svg>'].join(''); }
export function pxToMm(px: number, ppi: number) { return px * 25.4 / Math.max(1, ppi); }
export function mmToPx(mm: number, ppi: number) { return mm * Math.max(1, ppi) / 25.4; }
